# This workflow installs Node.js dependencies, caches them for faster builds,
# builds the source code if applicable, runs tests, and pushes build files to the repository.
# More info: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See the Node.js release schedule: https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build --if-present
      


      - name: Commit and push build files
        run: |
          git config --local user.name "shehabalqudiry"
          git config --local user.email "omran.shehab40@gmail.com"
          git add -f dist/
          git commit -m "Add build files" || echo "No changes to commit"
          git push origin main  # Ensure this matches your default branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

